config/routes.rb
require 'market_constraint'
require 'whitelist_constraint'

Rails.application.eager_load! if Rails.env.development?

Peatio::Application.routes.draw do

  root 'welcome#index'

  if Rails.env.development?
    mount MailsViewer::Engine => '/mails'
  end

  get '/signin' => 'sessions#new', :as => :signin
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  post '/auth/identity/callback' => 'sessions#create'

  resource :member, :only => [:edit, :update]
  resource :identity, :only => [:edit, :update]

  namespace :verify do
    resource :two_factor,  only: [:new, :create]
    resources :sms_tokens, only: [:new, :create]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
  end

  get '/documents/api_v2'
  get '/documents/websocket_api'
  resources :documents, only: [:show]
  resources :refresh_two_factors, only: [:show]

  scope module: 'private' do
    resource  :id_document, only: [:new, :create]

    resources :settings, only: [:index]
    resources :two_factors, only: [:show, :update, :edit, :destroy]
    resources :deposits, only: [:index, :destroy, :update]
    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name
      end
    end

    resources :withdraws, except: [:new]
    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :fund_sources, :only => [:index, :destroy]
    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:index, :destroy]
      resources :order_bids, :only => [:create]
      resources :order_asks, :only => [:create]
    end

    post '/pusher/auth', to: 'pusher#auth'
  end

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :documents
    resource :currency_deposit, :only => [:new, :create]
    resources :members, :only => [:index, :show, :update]
    resources :proofs

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    namespace :statistic do
      resource :members, :only => :show
      resource :orders, :only => :show
      resource :trades, :only => :show
      resource :deposits, :only => :show
      resource :withdraws, :only => :show
    end
  end

  constraints(WhitelistConstraint.new(JSON.parse(Figaro.env.try(:api_whitelist) || '[]'))) do
    namespace :api, defaults: {format: 'json'}, :constraints => MarketConstraint do
      scope module: :v1 do
        resources :deeps, :only => :show
        resources :trades, :only => :show
        resources :tickers, :only => :show
        resources :prices, :only => :show
      end
    end
  end

  get '/forum' => 'forum#index'

  mount APIv2::Mount => '/'

end

app/views/shared/_browser.html.slim
- unless browser.modern?
  #danger.dialog
    span.text-important
      i.fa.fa-bell
      == t('.modern')
    button.btn data-dismiss="alert" x

app/views/shared/_document.html.slim
#document_modal.modal.hide.fade tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  .modal-body
  .modal-footer: a.close data-dismiss='modal' aria-hidden='true' = t('.close')

app/views/shared/_empty_table.html.slim
table.table.table-bordered.table-empty
  thead: tr: th.text-center ......

app/views/shared/_flash.slim
.flash-message
  -if flash[:notice]
    #notice.alert.alert-dismissable.alert-success
      button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
      h5
        i.fa.fa-bullhorn
        span = flash[:notice]

  -if flash[:alert]
    #alert.alert.alert-dismissable.alert-warning
      button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
      h5
        i.fa.fa-info-circle
        span = flash[:alert]

  -if flash[:info]
    #info.alert.alert-dismissable.alert-info
      button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
      h5
        i.fa.fa-info-circle
        span = flash[:info]

app/views/shared/_footer.html.slim
footer: .container: .row: .col-md-12.text-center
  p
    | Maintained by the 
    a target='_blank' href='https://github.com/orgs/peatio/members' core team 
    | with the help of 
    a target='_blank' href='https://github.com/peatio/peatio/graphs/contributors' our contributors
    |.
  p 
    | Code licensed under 
    a target='_blank' href='http://peatio.mit-license.org/' MIT
    |, documentation under 
    a target='_blank' href='http://creativecommons.org/licenses/by/3.0/' CC BY 3.0
    |.
  p: ul.list-inline
    li: span Currently v#{Peatio::VERSION}
    li: a target='_blank' href='https://github.com/peatio/peatio' GitHub
    li: a target='_blank' href='https://github.com/peatio/peatio/tree/master/doc' Documents
    li: a target='_blank' href='https://github.com/peatio/peatio/wiki/About' About
    li: a target='_blank' href='https://github.com/peatio/peatio/issues?state=open' Issues
    li: a target='_blank' href='https://github.com/peatio/peatio/releases' Releases

app/views/shared/_footer_col24.html.slim
footer: .container: .row: .col-md-24.text-center
  p
    | Maintained by the
    a target='_blank' href='https://github.com/orgs/peatio/members' core team
    | with the help of
    a target='_blank' href='https://github.com/peatio/peatio/graphs/contributors' our contributors
    |.
  p
    | Code licensed under
    a target='_blank' href='http://peatio.mit-license.org/' MIT
    |, documentation under
    a target='_blank' href='http://creativecommons.org/licenses/by/3.0/' CC BY 3.0
    |.
  p: ul.list-inline
    li: span Currently v#{Peatio::VERSION}
    li: a target='_blank' href='https://github.com/peatio/peatio' GitHub
    li: a target='_blank' href='https://github.com/peatio/peatio/tree/master/doc' Documents
    li: a target='_blank' href='https://github.com/peatio/peatio/wiki/About' About
    li: a target='_blank' href='https://github.com/peatio/peatio/issues?state=open' Issues
    li: a target='_blank' href='https://github.com/peatio/peatio/releases' Releases

app/views/shared/_header.html.slim
header: .container
  = render 'shared/pusher'
  nav#top-menu.navbar.navbar-default role="navigation"
    = render 'shared/menu'

app/views/shared/_html5.html.slim
== "<!--[if lt IE 9]>"
= javascript_include_tag 'html5'
== "<![endif]-->"

app/views/shared/_market_selector.html.slim
ul#market_selector
  - Market.all.each do |market|
    li
      = link_to_unless_current market.name, main_app.market_path(market.id)

app/views/shared/_menu.html.slim
ul#menu.nav.navbar-nav.navbar-left
  = top_nav(t('header.market'), market_path(current_market), 'exchange', market_links)
  = top_nav_link(t('header.deposit'), deposits_path, 'credit-card', controllers: ['deposits'])
  = top_nav_link(t('header.withdraw'), withdraws_path, 'money', controllers: ['withdraws'])
  = top_nav_link(t('header.assets'), exchange_assets_path, 'bar-chart-o')
  = top_nav_link(t('header.history'), order_history_path, 'book')

ul.nav.navbar-nav.navbar-right
  - if current_user
    = top_nav_link(t('header.my_profile'), settings_path, 'user', controllers: ['two_factors', 'identities', 'id_documents'])
    - if is_admin?
      = top_nav_link('', admin_dashboard_path, 'dashboard')
    li: a#sign_out href='#{main_app.signout_path}'
      i.fa.fa-sign-out
      span = t('header.signout')
  - else
    = top_nav_link(t('header.signin'), signin_path, '')
    = top_nav_link(t('header.signup'), signup_path, '')

  li.dropdown
    a.dropdown-toggle href="#" data-toggle="dropdown"
      img src='#{language_path}'
      b.caret
    ul#languages.dropdown-menu
      - I18n.available_locales.each do |lang|
        li: a href="?lang=#{lang}": img src='#{language_path(lang)}'

app/views/shared/_meta.html.slim
title = i18n_meta('page_title')

meta name='description' content=i18n_meta('page_description')
meta name='keywords' content=i18n_meta('page_keywords')

app/views/shared/_muut.html.slim
button.btn.btn-success data-toggle='modal' data-target='#chat-modal' style='position: fixed; right: 0; top: 50%'
  i.fa.fa-comment

#chat-modal.modal.fade tabindex='-1' role="dialog" aria-labelledby="chatModal" aria-hidden="true"
  .modal-dialog
    .modal-content
      a#muut href='https://muut.com/i/peatio#{request.path}:chat' livechat

= content_for(:scripts)
  = javascript_include_tag "//cdn.muut.com/1/moot.#{I18n.locale.to_s.slice(0,2)}.min.js"
  = stylesheet_link_tag '//cdn.muut.com/1/moot.css'
  css:
    .is-commenting .m-comment-meta .m-seed { display: none }
    .is-commenting .m-comment_count { display: none }
  javascript:
    $(function(){
      $("#muut").muut({
        api: #{muut_api_options.to_json.html_safe}
      })

      $('#chat .expand').hide();
      $('#chat button.toggle').on('click', function(){
        $('#chat .expand').toggle();
        $('#chat .fold').toggle();
      })
    });

app/views/shared/_pusher.html.slim
.alert.alert-danger.alert-dismissable.pusher-unavailable.hide
  button.close type="button" data-dismiss="alert" aria-hidden="true" == "&times;"
  = t('.pusher_unavailable')
  a href="" = t('.refresh')

app/views/shared/_two_factor_auth.html.slim
.two-factor-auth-container
  .form-group.string.required
    - if app_activated && sms_activated
      label.string.required.col-sm-1.control-label
      .col-sm-10
        .input-group style="width:100%;"
          .input-group-btn
            button.btn.btn-default.dropdown-toggle href="javascript:;" data-toggle="dropdown" style="cursor:pointer;width:145px;"
              span.switch-name = t('private.two_factors.auth.google_app')
              span.caret style="margin-left:5px;"
            ul.dropdown-menu
              li: a data-type="app" href="javascript:;" = t('private.two_factors.auth.google_app')
              li: a data-type="sms" href="javascript:;" = t('private.two_factors.auth.sms')

          input.two_factor_auth_type type="hidden" name="two_factor[type]" value="app"
          input.string.required.form-control id="two_factor_otp" name="two_factor[otp]" min="100000" max="999999" type="number" placeholder=t('private.two_factors.auth.otp_placeholder')
          .input-group-btn.send-code-button.hide
            button.btn.btn-primary type='submit' name="commit" value="send_code" data-orig-name=t('private.two_factors.auth.send_code') data-alt-name=t('private.two_factors.auth.send_code_alt') = t('private.two_factors.auth.send_code')
      span.hint.app.col-sm-7.col-sm-offset-4 = t('private.two_factors.auth.hints.app')
      span.hint.sms.col-sm-7.col-sm-offset-4.hide = t('private.two_factors.auth.hints.sms')

    - elsif app_activated
      label.string.required.col-sm-4.control-label for="two_factor_otp"
        abbr == "*&nbsp;"
        span = t('private.two_factors.auth.google_app')

      .col-sm-7
        .input-group style="width:100%;"
          input.two_factor_auth_type type="hidden" name="two_factor[type]" value="app"
          input.string.required.form-control id="two_factor_otp" name="two_factor[otp]" min="100000" max="999999" type="number" placeholder=t('private.two_factors.auth.otp_placeholder')
      span.hint.app.col-sm-7.col-sm-offset-4 = t('private.two_factors.auth.hints.app')

    - elsif sms_activated
      label.string.required.col-sm-4.control-label for="two_factor_otp"
        abbr == "*&nbsp;"
        span = t('private.two_factors.auth.sms')

      .col-sm-7
        .input-group style="width:100%;"
          input.two_factor_auth_type type="hidden" name="two_factor[type]" value="sms"
          input.string.required.form-control id="two_factor_otp" name="two_factor[otp]" min="100000" max="999999" type="number" placeholder=t('private.two_factors.auth.otp_placeholder')

          .input-group-btn.send-code-button
            button.btn.btn-primary type='submit' name="commit" value="send_code" data-orig-name=t('private.two_factors.auth.send_code') data-alt-name=t('private.two_factors.auth.send_code_alt') = t('private.two_factors.auth.send_code')
      span.hint.sms.col-sm-7.col-sm-offset-4 = t('private.two_factors.auth.hints.sms')