config/routes.rb
require 'market_constraint'
require 'whitelist_constraint'

Rails.application.eager_load! if Rails.env.development?

Peatio::Application.routes.draw do

  root 'welcome#index'

  if Rails.env.development?
    mount MailsViewer::Engine => '/mails'
  end

  get '/signin' => 'sessions#new', :as => :signin
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  post '/auth/identity/callback' => 'sessions#create'

  resource :member, :only => [:edit, :update]
  resource :identity, :only => [:edit, :update]

  namespace :verify do
    resource :two_factor,  only: [:new, :create]
    resources :sms_tokens, only: [:new, :create]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
  end

  get '/documents/api_v2'
  get '/documents/websocket_api'
  resources :documents, only: [:show]
  resources :refresh_two_factors, only: [:show]

  scope module: 'private' do
    resource  :id_document, only: [:new, :create]

    resources :settings, only: [:index]
    resources :two_factors, only: [:show, :update, :edit, :destroy]
    resources :deposits, only: [:index, :destroy, :update]
    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name
      end
    end

    resources :withdraws, except: [:new]
    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :fund_sources, :only => [:index, :destroy]
    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:index, :destroy]
      resources :order_bids, :only => [:create]
      resources :order_asks, :only => [:create]
    end

    post '/pusher/auth', to: 'pusher#auth'
  end

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :documents
    resource :currency_deposit, :only => [:new, :create]
    resources :members, :only => [:index, :show, :update]
    resources :proofs

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    namespace :statistic do
      resource :members, :only => :show
      resource :orders, :only => :show
      resource :trades, :only => :show
      resource :deposits, :only => :show
      resource :withdraws, :only => :show
    end
  end

  constraints(WhitelistConstraint.new(JSON.parse(Figaro.env.try(:api_whitelist) || '[]'))) do
    namespace :api, defaults: {format: 'json'}, :constraints => MarketConstraint do
      scope module: :v1 do
        resources :deeps, :only => :show
        resources :trades, :only => :show
        resources :tickers, :only => :show
        resources :prices, :only => :show
      end
    end
  end

  get '/forum' => 'forum#index'

  mount APIv2::Mount => '/'

end

app/controllers/private/account_versions_controller.rb
module Private
  class AccountVersionsController < BaseController
    def index
      @account_versions_grid = AccountVersionsGrid.new(params[:account_versions_grid]) do |scope|
        scope.where(:member_id => current_user.id)
      end
      @assets = @account_versions_grid.assets.page(params[:page]).per(20)
    end
  end
end

app/controllers/private/assets_controller.rb
module Private
  class AssetsController < BaseController
    layout 'application', only: [:index]

    before_action :auth_activated!

    def index
      @cny_assets  = Currency.assets('cny')
      @btc_proof   = Proof.current :btc
      @cny_proof   = Proof.current :cny
      @btc_account = current_user.accounts.with_currency(:btc).first
      @cny_account = current_user.accounts.with_currency(:cny).first
    end

    def partial_tree
      account    = current_user.accounts.with_currency(params[:id]).first
      @timestamp = Proof.with_currency(params[:id]).last.timestamp
      @json      = account.partial_tree.to_json.html_safe
      respond_to do |format|
        format.js
      end
    end

  end
end

app/controllers/private/base_controller.rb
module Private
  class BaseController < ::ApplicationController
    before_filter :auth_member!

    private

    def verify_two_factor!
      return true unless current_user.two_factors_activated?

      two_factor = current_user.two_factors.by_type(:app)
      unless two_factor.verify(params[:two_factor][:otp])
        flash[:notice] = two_factor.errors[:otp].join
        redirect_to :back
      end
    end
  end
end

app/controllers/private/deposits/banks_controller.rb
module Private
  module Deposits
    class BanksController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlBankable
    end
  end
end

app/controllers/private/deposits/base_controller.rb
module Private
  module Deposits
    class BaseController < ::Private::BaseController
      before_action :channel
      before_action :auth_activated!
      before_action :auth_verified!

      def channel
        @channel ||= DepositChannel.find_by_key(self.controller_name.singularize)
      end

      def model_kls
        "deposits/#{self.controller_name.singularize}".camelize.constantize
      end
    end
  end
end

app/controllers/private/deposits/satoshis_controller.rb
module Private
  module Deposits
    class SatoshisController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits_controller.rb
module Private
  class DepositsController < BaseController
    def index
      @deposits = DepositChannel.all.sort
    end

    def update
      @deposit = current_user.deposits.find(params[:id])
      if @deposit.submit!
        redirect_to :back, notice: t('.notice')
      else
        redirect_to :back, alert: t('.alert')
      end
    end

    def destroy
      @deposit = current_user.deposits.find(params[:id])
      if @deposit.cancel!
        redirect_to :back, notice: t('.notice')
      else
        1/0
        redirect_to :back, alert: t('.alert')
      end
    end
  end
end

app/controllers/private/fund_sources_controller.rb
module Private
  class FundSourcesController < BaseController
    respond_to :json
    def index
      respond_with current_user.fund_sources.with_channel(params[:channel_id])
    end

    def destroy
      FundSource.where(
        member: current_user,
        uid: params[:id],
        is_locked: false).destroy_all
      head :ok
    end
  end
end

app/controllers/private/history_controller.rb
module Private
  class HistoryController < BaseController
    layout 'application'

    def account
      @market = current_market
      @deposits = Deposit.where(member: current_user).with_aasm_state(:accepted)
      @withdraws = Withdraw.where(member: current_user).with_aasm_state(:done)
      @buys = @sells = []
      gon.jbuilder controller: self
    end

    def trades
      @trades = current_user.trades
        .includes(:ask_member).includes(:bid_member)
        .order('id desc').page(params[:page]).per(20)
    end

    def orders
      @orders = current_user.orders.includes(:trades).order("id desc").page(params[:page]).per(20)
    end

  end
end

app/controllers/private/id_documents_controller.rb
module Private
  class IdDocumentsController < BaseController
    def new
      @id_document = IdDocument.new
    end

    def create
      @id_document = current_user.create_id_document(id_docuemnt_params)
      if @id_document.valid?
        redirect_to settings_path, notice: t('.notice')
      else
        render :new
      end
    end

    private
    def id_docuemnt_params
      params.require(:id_document).permit(:name, :sn, :category)
    end
  end
end

app/controllers/private/markets_controller.rb
module Private
  class MarketsController < BaseController
    after_filter :set_default_market

    layout 'market'

    def show
      @bid = params[:bid]
      @ask = params[:ask]

      @ask_name = I18n.t("currency.name.#{@ask}")
      @bid_name = I18n.t("currency.name.#{@bid}")

      @market = current_market

      @bids   = Global[@market].bids
      @asks   = Global[@market].asks
      @trades = Global[@market].trades
      @price  = Global[@market].price
      @ticker = Global[@market].ticker

      # default to limit order
      @order_bid = OrderBid.new ord_type: 'limit'
      @order_ask = OrderAsk.new ord_type: 'limit'

      @member = current_user

      @member.orders.with_currency(@market).tap do |query|
        @orders_wait = query.with_state(:wait)
        @orders_cancel = query.with_state(:cancel).last(5)
      end

      @trades_done = Trade.for_member(@market.id, current_user, limit: 100)

      gon.jbuilder
    end

    private

    def set_default_market
      cookies[:market_id] = @market.id
    end

  end
end

app/controllers/private/order_asks_controller.rb
module Private
  class OrderAsksController < BaseController
    include Concerns::OrderCreation

    def create
      @order = OrderAsk.new(order_params(:order_ask))
      order_submit
    end
  end
end

app/controllers/private/order_bids_controller.rb
module Private
  class OrderBidsController < BaseController
    include Concerns::OrderCreation

    def create
      @order = OrderBid.new(order_params(:order_bid))
      order_submit
    end
  end
end

app/controllers/private/orders_controller.rb
module Private
  class OrdersController < BaseController
    def destroy
      ActiveRecord::Base.transaction do
        order = current_user.orders.find(params[:id])
        ordering = Ordering.new(order)

        if ordering.cancel
          render status: 200, nothing: true
        else
          render status: 500, nothing: true
        end
      end
    end
  end
end

app/controllers/private/payment_addresses_controller.rb
module Private
  class PaymentAddressesController < BaseController
    def update
      account = current_user.get_account(params[:currency])
      payment_address = account.payment_addresses.using
      unless payment_address.transactions.empty?
        account.gen_payment_address
      end
      redirect_to funds_path
    end
  end
end

app/controllers/private/pusher_controller.rb
require "openssl"

module Private
  class PusherController < BaseController
    protect_from_forgery :except => :auth
  
    def auth
      sn = params[:channel_name].split('-', 2).last
      if current_user && current_user.sn == sn
        response = Pusher[params[:channel_name]].authenticate(params[:socket_id])
        render :json => response
      else
        render :text => "Forbidden", :status => '403'
      end
    end
  end
end

app/controllers/private/settings_controller.rb
module Private
  class SettingsController < BaseController
    def index
      unless current_user.activated?
        flash.now[:info] = t('.activated')
      end

      @accounts = current_user.accounts
      @two_factor = current_user.two_factors.by_type(:app).activated?
      @verified = (current_user.id_document and current_user.id_document_verified?)
    end
  end
end

app/controllers/private/trade_states_controller.rb
module Private
  class TradeStatesController < BaseController
    def show
      @member = current_user
      @ask_account = @member.get_account params[:ask]
      @bid_account = @member.get_account params[:bid]
    end
  end
end

app/controllers/private/two_factors_controller.rb
module Private
  class TwoFactorsController < BaseController
    before_action :fetch
    before_action :activated!, only: [:edit, :destroy]
    before_action :not_activated!, only: [:show, :create]

    def show
      @two_factor.refresh if params[:refresh]
      @two_factor.refresh if @two_factor.otp_secret.blank?
    end

    def edit
    end

    def update
      if two_factor_verified?
        @two_factor.active!
        redirect_to settings_path, notice: t('.notice')
      else
        flash[:alert] = t('.alert')
        redirect_to two_factor_path(:app)
      end
    end

    def destroy
      if two_factor_verified?
        @two_factor.inactive!
        redirect_to settings_path, notice: t('.notice')
      else
        flash[:alert] = t('.alert')
        render edit_two_factor_path(:app)
      end
    end

    private

    def fetch
      @two_factor = current_user.two_factors.by_type(:app)
    end

    def two_factor_params
      params.require(:two_factor).permit(:otp)
    end

    def two_factor_verified?
      @two_factor.assign_attributes(two_factor_params)
      @two_factor.verify
    end

    def activated!
      redirect_to settings_path if not @two_factor.activated?
    end

    def not_activated!
      redirect_to settings_path if @two_factor.activated?
    end
  end
end

app/controllers/private/withdraws/banks_controller.rb
module Private::Withdraws
  class BanksController < ::Private::Withdraws::BaseController
    include ::Withdraws::CtrlBankable
  end
end

app/views/private/settings/_account_balance.html.slim
.panel.panel-default.account-balance
  .panel-heading
    h2.panel-title = t('trade.account_balance.title')
  .panel-body
    .col-md-12
      table.table.table-condensed.table-striped
        thead: tr
          - %w(currency balance locked).each do |attr|
            th class='#{attr}' = Account.human_attribute_name(attr)
        tbody
          - @accounts.each do |account|
            tr class="#{account.currency}"
              td.name = t("currency.name.#{account.currency}", default: account.currency_obj.code.upcase)
              td.available = account.balance
              td.locked = account.locked

app/views/private/settings/index.html.slim
= content_for :before_content do
  .container = render partial: 'account_balance'

ul.list-group

  // member email activated
  li.list-group-item
    .row.row-middle
      .col-md-1
        i.fa.fa-envelope-o.fa-2x
      .col-md-8
        h4 = t('.email.title')
        - if current_user.activated?
          p.text-ignore = t('.email.description-activated')
        - else
          p.text-ignore = t('.email.description')
      .col-md-3
        - if current_user.activated?
          a href="#" class="btn btn-success btn-block disabled" role="button"
            i.fa.fa-check-circle
            span = t('.email.activated')
        - else
          = link_to t('.email.resend'), new_activation_path, class: 'btn btn-default btn-block'

  // id document verify
  li.list-group-item
    .row.row-middle
      .col-md-1
        i.fa.fa-thumbs-o-up.fa-2x
      .col-md-8
        h4
          span = t('.verification.title')
          i.fa.fa-bolt.text-warning
        p.text-ignore = t('.verification.description')
      .col-md-3
        - if @verified
          a href="#" class="btn btn-success btn-block disabled" role="button"
            i.fa.fa-check-circle
            span = t('.verification.verified')
        - else
          = link_to t('.verification.go'), new_id_document_path, class: 'btn btn-default btn-block'

  // phone number verify
  li.list-group-item
    .row.row-middle
      .col-md-1
        i.fa.fa-mobile.fa-4x
      .col-md-8
        h4
          span = t('.phone_number.title')
          i.fa.fa-bolt.text-warning
        p.text-ignore = t('.phone_number.description')
      .col-md-3
        - if current_user.phone_number_verified?
          a href="#" class="btn btn-success btn-block disabled" role="button"
            i.fa.fa-check-circle
            span = t('.phone_number.verified')
        - else
          = link_to t('.phone_number.go'), new_verify_sms_token_path, class: 'btn btn-default btn-block'

  // two factor setting
  li.list-group-item
    #two_factor_auth.row.row-middle
      .col-md-1
        i.fa.fa-superscript.fa-2x
      .col-md-8
        h4
          span = t('.two_factor_auth.title')
          i.fa.fa-bolt.text-warning
        p.text-ignore = t('.two_factor_auth.description')
      .col-md-3
        - if @two_factor
          = link_to t('.two_factor_auth.disable'), edit_two_factor_path(:app), class: 'btn btn-default btn-block'
        - else
          = link_to t('.two_factor_auth.enable'), two_factor_path(:app), class: 'btn btn-default btn-block'

  // change identity password
  - if current_user.identity
    li.list-group-item
      .row.row-middle
        .col-md-1
          i.fa.fa-key.fa-2x
        .col-md-8
          h4 = t('.passwords.title')
          p.text-ignore = t('.passwords.description')
        .col-md-3
          = link_to t('.passwords.go'), edit_identity_path, class: 'btn btn-default btn-block'

= content_for :guide_title do
  h3
    i.fa.fa-user
    span = current_user.email

= content_for :guide do
  ul.list-group
    - if current_user.admin?
      span.label.label-warning ADMIN
    - current_user.tag_list.each do |key|
      span.label.label-info
        = member_tag(key)
  p.text-warning
    == t('.safety_instruction')